### ISSUE TITLE
Issue with spaces in folder names

### ISSUE THREAD

**Issue by ZeroCrunch** [markfinal/BuildAMation#449]
I download BAM to the default location. Extracted. CD'd into that folder.

This results in the path "C:\Users\Jamie Kenyon\Downloads\BuildAMation-1.2.0a3-AnyCPU"

Issuing the "env" command then results in:

```
C:\Users\Jamie Kenyon\Downloads\BuildAMation-1.2.0a3-AnyCPU>env
The system cannot find the path specified.
*** ERROR: BuildAMation directory 'C:\Users\Jamie Kenyon\Downloads\BuildAMation-1.2.0a3-AnyCPU\bin\Release' does not exist ***
BuildAMation (Bam) v1.2.0a3 (c) Mark Final, 2010-2018. Licensed under BSD 3-clause. See License.md.
Parts of this software are licensed under the Microsoft Limited Public License (MS-PL). See MS-PL.md.
Using CLR v4.0.30319.42000 (.NET Framework 4.5) with assemblies in C:\Users\Jamie Kenyon\Downloads\BuildAMation-1.2.0a3-AnyCPU\bin\Release
```

**Comment by markfinal** [comment]
Shucks, noobie coding error in batch files!

I've reproduced it. Easy to fix (add quotes, or do something with delayed expansion in the batch file) but I'll check the bash script at the same time.
