### ISSUE TITLE
Persistent environment

### ISSUE THREAD

**Issue by ZeroCrunch** [markfinal/BuildAMation#456]
Technically not an issue, more of a request.

Instinctively when I double-click env.bat, I expect the command window to stay open with the environment set.

Would it be possible to end the script with "cmd /k" to keep the window open please?

**Comment by markfinal** [comment]
Interesting, never tried it like that. I always open a fresh CMD prompt, cd to the install directory, and then type env.

I was under the impression that you need something like a shortcut file in order to do `cmd /k env.bat`. 

I'll give your idea a whirl though.

**Comment by ZeroCrunch** [comment]
IMHO, I think thats a difference in Linux vs Windows thinking. Generally, we just double click things and expect them to work. For example, the VS command prompts that are in the Start Menu.

The only time I'd do something like `cmd /k env.bat` is if I was chaining batch files.

**Comment by markfinal** [comment]
I won't disagree.
The VS command prompts in the Start Menu are Shortcut links though, not the real batch files. So that's at least one possible solution, to provide one of them.

**Comment by markfinal** [comment]
I've got a solution.

Although adding cmd /k to the end of the existing env.bat did persist the cmd shell if you just double clicked on env.bat in Windows Explorer, if you used my approach of running env.bat within an already open cmd shell, then you get a nested shell, e.g. you have to type exit twice to eventually close the window. That didn't work well for me.

Adding an .lnk to a git repository is apparently nightmarish (https://stackoverflow.com/questions/33608937/how-to-track-lnk-files-in-git), so I've compromised.

I've added a Powershell script to the top level of the BAM archive which, when run, generates a shortcut file to `%comspec% /K env.bat`.
Both mechanisms for using it are thus honoured.
